"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import AppShell from "@/components/app/AppShell";
import FeatureIntro from "@/components/app/FeatureIntro";
import type { BookChapter } from "@/lib/agents";

interface ChapterPlan {
  number: number;
  title: string;
  part: string;
}

const PARTS = [
  { name: "Part 1: Who You Are Today", chapters: [1, 2, 3] },
  { name: "Part 2: Where the World Is Going", chapters: [4, 5, 6] },
  { name: "Part 3: Your Personalized Roadmap", chapters: [7, 8, 9, 10] },
  { name: "Part 4: Your Toolkit", chapters: [11, 12, 13, 14] },
  { name: "Part 5: Your Story", chapters: [15, 16] },
];

export default function BookPage() {
  const [chapters, setChapters] = useState<BookChapter[]>([]);
  const [chapterPlan, setChapterPlan] = useState<ChapterPlan[]>([]);
  const [generating, setGenerating] = useState(false);
  const [currentChapter, setCurrentChapter] = useState(0);
  const [selectedChapter, setSelectedChapter] = useState<number | null>(null);
  const [snapshot, setSnapshot] = useState<Record<string, unknown> | null>(null);
  const [caiiReport, setCaiiReport] = useState<Record<string, unknown> | null>(null);
  const [roadmap, setRoadmap] = useState<Record<string, unknown> | null>(null);
  const [wins, setWins] = useState<Record<string, unknown>[]>([]);

  // Load data
  useEffect(() => {
    const s = localStorage.getItem("legacyforward_snapshot");
    if (s) try { setSnapshot(JSON.parse(s)); } catch { /* */ }
    const c = localStorage.getItem("legacyforward_caii");
    if (c) try { setCaiiReport(JSON.parse(c)); } catch { /* */ }
    const r = localStorage.getItem("legacyforward_roadmap");
    if (r) try { setRoadmap(JSON.parse(r)); } catch { /* */ }
    const w = localStorage.getItem("legacyforward_wins");
    if (w) try { setWins(JSON.parse(w)); } catch { /* */ }
    const b = localStorage.getItem("legacyforward_book");
    if (b) try { const book = JSON.parse(b); setChapters(book); if (book.length > 0) setSelectedChapter(1); } catch { /* */ }

    // Fetch chapter plan
    fetch("/api/book").then(r => r.json()).then(d => setChapterPlan(d.plan)).catch(() => {});
  }, []);

  async function generateBook() {
    setGenerating(true);
    setChapters([]);
    setSelectedChapter(null);

    const userName = (snapshot?.currentRole as string) ? (snapshot?.narrativeSummary as string)?.split(" ")[0] || "you" : "you";
    const generated: BookChapter[] = [];

    for (let i = 0; i < 16; i++) {
      setCurrentChapter(i + 1);
      try {
        const res = await fetch("/api/book", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            chapterIndex: i,
            snapshot,
            caiiReport,
            roadmap,
            wins,
            marketCode: "US",
            userName,
          }),
        });
        const chapter = await res.json();
        generated.push(chapter);
        setChapters([...generated]);
        if (i === 0) setSelectedChapter(1);
      } catch {
        generated.push({
          number: i + 1,
          title: chapterPlan[i]?.title || `Chapter ${i + 1}`,
          content: "Failed to generate this chapter. Please try regenerating.",
          wordCount: 0,
        });
        setChapters([...generated]);
      }
    }

    localStorage.setItem("legacyforward_book", JSON.stringify(generated));
    setGenerating(false);
  }

  function downloadAsText() {
    const text = chapters
      .map((c) => `# Chapter ${c.number}: ${c.title}\n\n${c.content}`)
      .join("\n\n---\n\n");

    const header = `YOUR CAREER BIBLE\nGenerated by LegacyForward.ai · ${new Date().toLocaleDateString()}\n${"=".repeat(50)}\n\n`;
    const blob = new Blob([header + text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "LegacyForward.ai-Career-Bible.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  const totalWords = chapters.reduce((sum, c) => sum + c.wordCount, 0);
  const activeChapter = chapters.find((c) => c.number === selectedChapter);
  const hasData = !!snapshot?.currentRole;

  return (
    <AppShell>
          <FeatureIntro
            id="book"
            title="Your Personalized Career Bible — No One Else Gets This Book"
            description="This isn't a generic career guide — it's a 16-chapter book written specifically about YOUR career using your Snapshot, CAII report, roadmap, and achievements. Each chapter addresses your real situation: your current role, your AI exposure, your skill gaps, and your target path. It's the career guide you wish existed — written just for you."
            color="purple"
          />
          {/* No book yet — generate */}
          {chapters.length === 0 && !generating && (
            <div>
              <div className="bg-gradient-to-r from-navy-800 to-teal-900 rounded-2xl p-8 text-white text-center mb-6">
                <div className="text-4xl mb-4">📖</div>
                <h1 className="text-2xl font-extrabold mb-2">Your Career Bible</h1>
                <p className="text-sm opacity-90 max-w-lg mx-auto mb-6">
                  A personalized 16-chapter career guide generated from your Career Snapshot, AI Impact Report, Roadmap, and achievements. No one else can get this book — it&apos;s built from YOUR data.
                </p>
                {hasData ? (
                  <button
                    onClick={generateBook}
                    className="px-8 py-3 bg-white text-teal-700 rounded-lg text-sm font-bold hover:bg-indigo-50 transition"
                  >
                    Generate Your Career Bible
                  </button>
                ) : (
                  <div>
                    <p className="text-sm opacity-70 mb-3">Complete onboarding first to personalize your book.</p>
                    <Link href="/app/onboarding" className="px-6 py-2 bg-white text-teal-700 rounded-lg text-sm font-semibold">
                      Start Onboarding →
                    </Link>
                  </div>
                )}
              </div>

              {/* Chapter preview */}
              <div className="bg-white border border-slate-200 rounded-xl p-5">
                <h3 className="text-sm font-bold text-slate-700 mb-4">What&apos;s Inside (16 Chapters)</h3>
                <div className="space-y-3">
                  {PARTS.map((part) => (
                    <div key={part.name}>
                      <div className="text-xs font-semibold text-slate-500 mb-1">{part.name}</div>
                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
                        {part.chapters.map((num) => {
                          const plan = chapterPlan[num - 1];
                          return (
                            <div key={num} className="px-3 py-2 bg-slate-50 rounded-lg text-xs text-slate-600">
                              <span className="font-semibold text-teal-600">Ch {num}.</span>{" "}
                              {plan?.title || `Chapter ${num}`}
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Generating */}
          {generating && (
            <div>
              <div className="bg-white border border-slate-200 rounded-xl p-6 mb-6">
                <div className="flex justify-between items-center mb-4">
                  <h2 className="text-lg font-bold">Generating Your Career Bible...</h2>
                  <span className="text-sm text-teal-600 font-semibold">
                    Chapter {currentChapter} of 16
                  </span>
                </div>
                <div className="h-3 bg-slate-100 rounded-full mb-2">
                  <div
                    className="h-full bg-gradient-to-r from-teal-500 to-teal-700 rounded-full transition-all duration-500"
                    style={{ width: `${(chapters.length / 16) * 100}%` }}
                  />
                </div>
                <div className="grid grid-cols-8 md:grid-cols-16 gap-1 mt-4">
                  {Array.from({ length: 16 }, (_, i) => (
                    <div
                      key={i}
                      className={`h-8 rounded flex items-center justify-center text-[10px] font-bold ${
                        i < chapters.length
                          ? "bg-teal-600 text-white"
                          : i === chapters.length
                          ? "bg-indigo-100 text-teal-600 animate-pulse"
                          : "bg-slate-100 text-slate-400"
                      }`}
                    >
                      {i + 1}
                    </div>
                  ))}
                </div>
              </div>

              {/* Show generated chapters as they come in */}
              {chapters.length > 0 && (
                <div className="bg-white border border-slate-200 rounded-xl p-6">
                  <h3 className="text-sm font-bold text-slate-700 mb-2">
                    Chapter {chapters[chapters.length - 1].number}: {chapters[chapters.length - 1].title}
                  </h3>
                  <div className="text-sm text-slate-600 leading-relaxed prose prose-sm max-w-none">
                    {chapters[chapters.length - 1].content.split("\n").map((p, i) => (
                      <p key={i} className="mb-2">{p}</p>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Book Reader */}
          {chapters.length === 16 && !generating && (
            <div>
              {/* Header */}
              <div className="bg-gradient-to-r from-navy-800 to-teal-900 rounded-2xl p-6 text-white mb-6 flex gap-6 items-center">
                {/* Mini book cover */}
                <div className="w-28 h-40 bg-white rounded-sm shadow-lg flex flex-col items-center justify-center p-3 shrink-0" style={{ borderRadius: "2px 10px 10px 2px" }}>
                  <div className="text-[8px] text-teal-600 font-bold uppercase tracking-wider">Your Career Bible</div>
                  <div className="w-8 h-0.5 bg-teal-600 my-1.5" />
                  <div className="text-[11px] font-extrabold text-slate-900 text-center">
                    {(snapshot?.currentRole as string) || "Your Name"}
                  </div>
                  <div className="text-[7px] text-slate-500 mt-auto">LegacyForward.ai · 2026</div>
                </div>
                <div className="flex-1">
                  <h1 className="text-xl font-extrabold">Your Career Bible</h1>
                  <p className="text-sm opacity-80 mt-1">
                    16 chapters · {totalWords.toLocaleString()} words · Generated <span suppressHydrationWarning>{new Date().toLocaleDateString()}</span>
                  </p>
                  <div className="flex gap-3 mt-4">
                    <button
                      onClick={downloadAsText}
                      className="px-4 py-2 bg-white text-teal-700 rounded-lg text-xs font-semibold hover:bg-indigo-50 transition"
                    >
                      📄 Download (Markdown)
                    </button>
                    <button
                      onClick={() => { setChapters([]); localStorage.removeItem("legacyforward_book"); }}
                      className="px-4 py-2 bg-white/15 text-white rounded-lg text-xs font-semibold hover:bg-white/25 transition border border-white/30"
                    >
                      🔄 Regenerate
                    </button>
                  </div>
                </div>
              </div>

              {/* Reader */}
              <div className="grid grid-cols-1 lg:grid-cols-[240px_1fr] gap-6">
                {/* Chapter nav */}
                <div className="bg-white border border-slate-200 rounded-xl p-4 h-fit lg:sticky lg:top-4">
                  <div className="text-xs font-bold text-slate-700 mb-3">Chapters</div>
                  <div className="space-y-0.5">
                    {PARTS.map((part) => (
                      <div key={part.name}>
                        <div className="text-[10px] font-semibold text-slate-400 mt-2 mb-1">{part.name}</div>
                        {part.chapters.map((num) => {
                          const ch = chapters.find(c => c.number === num);
                          return (
                            <button
                              key={num}
                              onClick={() => setSelectedChapter(num)}
                              className={`w-full text-left px-2 py-1.5 rounded text-xs ${
                                selectedChapter === num
                                  ? "bg-indigo-50 text-teal-600 font-semibold"
                                  : "text-slate-600 hover:bg-slate-50"
                              }`}
                            >
                              {num}. {ch?.title}
                            </button>
                          );
                        })}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Chapter content */}
                <div className="bg-white border border-slate-200 rounded-xl p-6 md:p-8">
                  {activeChapter ? (
                    <>
                      <div className="text-[10px] text-teal-600 font-semibold uppercase tracking-widest">
                        Chapter {activeChapter.number}
                      </div>
                      <h2 className="text-xl font-extrabold text-slate-900 mt-1 mb-6">
                        {activeChapter.title}
                      </h2>
                      <div className="text-sm text-slate-700 leading-relaxed space-y-3">
                        {activeChapter.content.split("\n").filter(Boolean).map((p, i) => (
                          <p key={i} dangerouslySetInnerHTML={{
                            __html: p
                              .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                              .replace(/\*(.*?)\*/g, "<em>$1</em>")
                          }} />
                        ))}
                      </div>
                      {/* Nav */}
                      <div className="flex justify-between mt-8 pt-4 border-t border-slate-100">
                        <button
                          onClick={() => setSelectedChapter(Math.max(1, (selectedChapter || 1) - 1))}
                          disabled={selectedChapter === 1}
                          className="text-sm text-slate-400 hover:text-teal-600 disabled:opacity-30"
                        >
                          ← Previous
                        </button>
                        <span className="text-xs text-slate-400">{activeChapter.wordCount} words</span>
                        <button
                          onClick={() => setSelectedChapter(Math.min(16, (selectedChapter || 1) + 1))}
                          disabled={selectedChapter === 16}
                          className="text-sm text-teal-600 font-semibold hover:underline disabled:opacity-30"
                        >
                          Next →
                        </button>
                      </div>
                    </>
                  ) : (
                    <p className="text-sm text-slate-500">Select a chapter to read.</p>
                  )}
                </div>
              </div>
            </div>
          )}
    </AppShell>
  );
}
